name: Feature Request
description: Suggest a new feature or enhancement for the NBA Command Palette Extension
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving the NBA Command Palette Extension! Please describe the feature you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Game Information
        - Player/Team Stats
        - Search & Filtering
        - User Preferences
        - UI/UX Enhancement
        - Performance
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Another approach could be...
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature? Provide a specific example.
      placeholder: |
        When watching games, I want to...
        So that I can...
    validations:
      required: false

  - type: checkboxes
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - label: Nice to have
        - label: Would significantly improve my experience
        - label: Critical for my workflow

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request here
      placeholder: Drag and drop images or provide links...
    validations:
      required: false
